// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABYnL5IX0fDvza9ynRJ9Pq5eb3Rw9iVTo',
    appId: '1:632588235595:web:80b6123886fd14b21f6ece',
    messagingSenderId: '632588235595',
    projectId: 'learnfirebase-59d27',
    authDomain: 'learnfirebase-59d27.firebaseapp.com',
    storageBucket: 'learnfirebase-59d27.appspot.com',
    measurementId: 'G-NJK3S9HYBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArtkYO8nG4gGI20p5VsbbmHY9hwx0w-rQ',
    appId: '1:632588235595:android:d886439a1fa171881f6ece',
    messagingSenderId: '632588235595',
    projectId: 'learnfirebase-59d27',
    storageBucket: 'learnfirebase-59d27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBTUTk_VUwlaa9hYNSeFTJb7J5HyEGFdI',
    appId: '1:632588235595:ios:ea5b50aed8ec83861f6ece',
    messagingSenderId: '632588235595',
    projectId: 'learnfirebase-59d27',
    storageBucket: 'learnfirebase-59d27.appspot.com',
    iosClientId: '632588235595-9nhi6tpe9kti3c80g3fp5rnpegkapjfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBTUTk_VUwlaa9hYNSeFTJb7J5HyEGFdI',
    appId: '1:632588235595:ios:f81eee4a88536cd81f6ece',
    messagingSenderId: '632588235595',
    projectId: 'learnfirebase-59d27',
    storageBucket: 'learnfirebase-59d27.appspot.com',
    iosClientId: '632588235595-rds2v5sj5bh10j25gut9dtb4g1g5op48.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFirebase.RunnerTests',
  );
}
